### ISSUE TITLE
Xcode 8.3 crash

### ISSUE THREAD

**Issue by k0Iry** [AlayshChen/XcodeAppPluginTemplate#1]
as title means

**Comment by k0Iry** [comment]
不给target name会crash，第一次用，不知道算不算bug

**Comment by ChiChou** [comment]
此外升级到 Xcode 8.3 之后会无法链接 cocoapods 的库：



`ld: warning: directory not found for option '-L/Users/***/Library/Developer/Xcode/DerivedData/NoRecall-gtltcobfpcvpvhekbaimltftusta/Build/Products/Debug/JRSwizzle'`

`ld: library not found for -lJRSwizzle`

**Comment by AlayshChen** [comment]
已更新App Target Name 和 App Target Bundle Id为必须字段

**Comment by k0Iry** [comment]
谢谢作者
