### ISSUE TITLE
编译的时候遇到的错误

### ISSUE THREAD

**Issue by NuolanNuolan** [AlayshChen/XcodeAppPluginTemplate#2]
<img width="1016" alt="default" src="https://cloud.githubusercontent.com/assets/18475995/24491702/04506dee-155b-11e7-83e2-e4b63f48052a.png">
提示没有insert_dylib 这个insert_dylib怎么安装呢?

**Comment by AlayshChen** [comment]
Please read readme first.

**Comment by NuolanNuolan** [comment]
<img width="652" alt="default" src="https://cloud.githubusercontent.com/assets/18475995/24493046/f771e2f6-155f-11e7-864b-61deb7980d6d.png">
我已经安装了insert_dylib了啊 但是编译还是报错 还请指教

**Comment by AlayshChen** [comment]
放在/usr/local/bin
