### ISSUE TITLE
如果包里已有第三方framework的话，此模板无法自动签名

### ISSUE THREAD

**Issue by molon** [AlayshChen/XcodeAppPluginTemplate#3]
如题~
请教有没有什么好的方式处理呢。

**Comment by AlayshChen** [comment]
在Run Script中添加脚本 /usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} --timestamp=none "${APP_NAME}/Frameworks/**(name).framework"

**Comment by molon** [comment]
@AlayshChen 非常感谢~ 然后发现每次都去签名实在浪费时间，现在直接手动签名了一次移到app里~
