### ISSUE TITLE
不一定是个issue

### ISSUE THREAD

**Issue by k0Iry** [AlayshChen/XcodeAppPluginTemplate#5]
你好，想问一下，Xcode 9之后，用该模版，在编译通过安装的过程中一直出现"App installation failed" "An unknown error has occurred"，有空你那边帮忙确认一下，谢谢

**Comment by k0Iry** [comment]
可能是代码签名的原因

**Comment by AlayshChen** [comment]
抱歉，回复晚了，我使用Xcode9.0 (9A235)测试了是没问题，一般安装失败是签名问题，具体失败log可以在Xcode Device中查看。可以尝试做如下操作。
1. 在工程设置中，检查插件framework 签名Team和app 签名Team是否一致。
2. 提供的app中已有内嵌framework，工程模版未对此进行重签名，可以在Run Script中添加相对应签名脚本。
/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} --timestamp=none "${APP_NAME}/Frameworks/**(name).framework"

**Comment by k0Iry** [comment]
thx, 是签名的原因，加了codesign脚本可以了
